site_name: AWD v2.4 Docs
site_url: https://awd.docs.atinyshellscript.com
site_author: aTinyShellScript

# Repository
repo_name: aTinyShellScript/v2.4_AWD
repo_url: https://github.com/aTinyShellScript/v2.4_AWD
edit_uri: "https://github.com/aTinyShellScript/awd_docs/tree/master/docs"

# Copyright
copyright: Copyright &copy; 2023 aTinyShellScript

# Config
theme:
  name: material
  logo: images/atss.png
  favicon: images/atss.png
  custom_dir: overrides

  include_search_page: false
  search_index_only: true
  
  language: en
  features:
    - announce.dismiss
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
      primary: deep purple
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
      primary: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Sourcing: sourcing.md
  - Metal Plates: metal_parts.md
  - Printed Plates: printed_parts.md
  - Setup & Config: configuration.md
  - Micron: micron.md
  - FAQ: faq.md
  - Contact: contact.md