site_name: v2.4 AWD Mod Documentation
site_url: https://awd.docs.atinyshellscript.com
site_author: aTinyShellScript

# Repository
repo_name: aTinyShellScript/v2.4_AWD
repo_url: https://github.com/aTinyShellScript/v2.4_AWD
edit_uri: "https://github.com/aTinyShellScript/awd_docs/tree/master/docs"

# Copyright
copyright: Copyright &copy; 2023 aTinyShellScript

# Config
theme:
  name: material

  include_search_page: false
  search_index_only: true
  
  language: en
  features:
    - announce.dismiss
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: atss
      accent: atss
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      default: atss-dark
      primary: atss-dark
      accent: atss-dark
  font:
    text: Roboto
    code: Roboto Mono
  #favicon: assets/favicon.png
  #logo: assets/images/logotype.svg
  icon:
    logo: logo

nav:
  - Home: index.md
  - Sourcing: sourcing.md
  - Metal Plates: metal_parts.md
  - Printed Plates: printed_parts.md
  - FAQ: faq.md
  - Contact: contact.md